
name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        export ACCEPT_EULA=Y
        sudo apt-get update
        python -m pip install --upgrade pip
        sudo apt-get install -y python3-pip libgdal-dev locales
        sudo apt-get install -y libspatialindex-dev
        export CPLUS_INCLUDE_PATH=/usr/include/gdal
        export C_INCLUDE_PATH=/usr/include/gdal
        sudo apt-get install ca-certificates
        export CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
        pip install GDAL==3.0.2
        pip install -e .
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=scripts,tests,osmread
    - name: Run tests
      run: |
        export CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
        ./scripts/code-coverage.sh
