name: Build Package

on:
  push:
    tags:
      - 'v*'

jobs:
  conda-build:
    uses: arup-group/actions-city-modelling-lab/.github/workflows/conda-build.yml@v1.1.0
    secrets:
      ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
    with:
      package_name: osmox
      environment: pre-release
      destination: pypi

  
  
