name: Publish

on:
  release:
    types: [released]

jobs:
  conda-upload:
    uses: arup-group/actions-city-modelling-lab/.github/workflows/conda-upload.yml@v1.1.0
    secrets:
      ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
    with:
      package_name: osmox
      build_workflow: pre-release.yml
      environment: release
      destination: anaconda

  
  
  docs-stable:
    permissions:
      contents: write
    uses: arup-group/actions-city-modelling-lab/.github/workflows/docs-deploy.yml@v1.1.0
    with:
      deploy_type: update_stable
